# See the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
    versioning-strategy: increase
    commit-message:
      prefix: 'chore(deps)'
    groups:
      commitlint:
        patterns:
          - '@commitlint/*'
    reviewers:
      - 'aboviq/maintainers'

  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'weekly'
    commit-message:
      prefix: 'chore(deps)'
    reviewers:
      - 'aboviq/maintainers'
